"use client";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { LoaderCircle, MapPin, ShieldCheck } from "lucide-react";
type RequestInfo = { tracking_number: string; customer_name: string | null; expires_at: string };
export default function ShareCustomerLocationPage() {
  const { token } = useParams<{ token: string }>(); const [info,setInfo]=useState<RequestInfo|null>(null); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(false); const [precision,setPrecision]=useState<number|null>(null);
  useEffect(()=>{let active=true;fetch("/api/customer-location-requests/"+encodeURIComponent(token),{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);if(active)setInfo(d);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Enlace inválido o vencido.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[token]);
  function sendLocation(){if(!window.isSecureContext||!navigator.geolocation){setError("Para compartir ubicación, abre este enlace mediante HTTPS.");return;}setSending(true);setError("");navigator.geolocation.getCurrentPosition(async pos=>{try{const r=await fetch("/api/customer-location-requests/"+encodeURIComponent(token),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy})});const d=await r.json();if(!r.ok)throw new Error(d.message||"No fue posible enviar la ubicación.");setPrecision(pos.coords.accuracy);setSuccess(true);}catch(e){setError(e instanceof Error?e.message:"No fue posible enviar la ubicación.");}finally{setSending(false);}},e=>{setError(e.code===e.PERMISSION_DENIED?"No se autorizó la ubicación. Permítela en los ajustes del navegador e inténtalo de nuevo.":"No se pudo obtener la ubicación. Revisa el GPS e inténtalo de nuevo.");setSending(false);},{enableHighAccuracy:true,timeout:20000,maximumAge:0});}
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-4 dark:bg-slate-950"><section className="w-full max-w-md rounded-3xl border border-sky-200 bg-white p-6 shadow-xl dark:border-slate-700 dark:bg-slate-900"><div className="mb-5 flex items-center gap-3"><div className="rounded-2xl bg-sky-100 p-3 text-sky-700 dark:bg-sky-950 dark:text-sky-300"><MapPin size={25}/></div><div><div className="text-xs font-semibold uppercase tracking-widest text-sky-700 dark:text-sky-300">Agiliza · ubicación</div><h1 className="text-xl font-bold">Compartir ubicación</h1></div></div>{loading?<div className="flex items-center gap-2 text-slate-500"><LoaderCircle className="animate-spin"/>Validando enlace…</div>:error&&!info?<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>:success?<div className="rounded-2xl bg-emerald-50 p-4 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-100"><div className="flex items-center gap-2 font-bold"><ShieldCheck/>Ubicación enviada correctamente</div><p className="mt-2 text-sm">Precisión aproximada: ±{Math.round(precision??0)} metros. Ya puedes cerrar esta página.</p></div>:info&&<><p className="text-slate-600 dark:text-slate-300">Envía tu ubicación actual para coordinar la entrega del envío <strong>{info.tracking_number}</strong>. Solo se compartirá al pulsar el botón.</p><button type="button" onClick={sendLocation} disabled={sending} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-sky-700 px-4 py-3 font-semibold text-white hover:bg-sky-800 disabled:opacity-60">{sending&&<LoaderCircle className="animate-spin" size={19}/>}<MapPin size={19}/>{sending?"Obteniendo y enviando…":"Enviar mi ubicación"}</button>{error&&<p role="alert" className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950 dark:text-amber-100">{error}</p>}<p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Enlace privado de un solo uso, válido por 24 horas. La precisión depende del GPS del dispositivo.</p></>}</section></main>;
}