"use client";

import { useEffect, useMemo, useState } from "react";
import { getRoutesOptions } from "@/modules/routes/api/get-routes-options";

type Props = { routeId: string; routeName: string; rateCount: number; shipmentCount: number; onClose: () => void; onConfirm: (successorRouteId: string | null) => Promise<void> };
export function RouteDeleteDialog({ routeId, routeName, rateCount, shipmentCount, onClose, onConfirm }: Props) {
  const [inheritShipments, setInheritShipments] = useState(false);
  const [routes, setRoutes] = useState<{ id: string; name: string; active: boolean }[]>([]);
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (inheritShipments) void getRoutesOptions().then((items) => setRoutes(items.filter((route) => route.id !== routeId && route.active))); }, [inheritShipments, routeId]);
  const filtered = useMemo(() => routes.filter((route) => route.name.toLowerCase().includes(search.toLowerCase())), [routes, search]);
  async function submit() { if (inheritShipments && !selected) return; setSaving(true); try { await onConfirm(inheritShipments ? selected : null); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-[450] flex items-center justify-center bg-black/40 p-4"><section className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900"><h2 className="text-lg font-bold">Eliminar ruta</h2><p className="mt-2 text-sm">Ruta: <strong>{routeName}</strong>.</p>{rateCount > 0 && <p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/40 dark:text-amber-100">Se eliminarán {rateCount} {rateCount === 1 ? "tarifa de mensajero asociada" : "tarifas de mensajero asociadas"}.</p>}{shipmentCount > 0 && <><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">Esta ruta tiene {shipmentCount} {shipmentCount === 1 ? "envío asignado" : "envíos asignados"}.</p><label className="mt-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={inheritShipments} onChange={(event) => setInheritShipments(event.target.checked)} /> <span><strong>Heredar envíos a otra ruta</strong><br />Seleccione una ruta activa para reasignar los envíos antes de eliminar.</span></label>{inheritShipments && <div className="mt-4 space-y-2"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar ruta..." className="w-full rounded-lg border p-2 dark:bg-slate-800" /><div className="max-h-44 overflow-auto rounded-lg border">{filtered.map((route) => <button key={route.id} type="button" onClick={() => setSelected(route.id)} className={`block w-full px-3 py-2 text-left text-sm ${selected === route.id ? "bg-sky-100 dark:bg-sky-900" : "hover:bg-slate-100 dark:hover:bg-slate-800"}`}>{route.name}</button>)}</div></div>}</>}<div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={onClose} disabled={saving} className="rounded-xl border py-3">Cancelar</button><button type="button" onClick={() => void submit()} disabled={saving || (inheritShipments && !selected)} className="rounded-xl bg-red-600 py-3 font-medium text-white disabled:opacity-50">{inheritShipments ? "Heredar y eliminar" : "Eliminar ruta"}</button></div></section></div>;
}