"use client";
import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import Chip from "@mui/material/Chip";
import { MaterialReactTable, type MRT_ColumnDef } from "material-react-table";
import { MRT_Localization_ES } from "material-react-table/locales/es";
import { RotateCcw } from "lucide-react";
import { standardMrtFeatures } from "@/shared/config/material-react-table";
import { createClient } from "@/lib/supabase/client";

type Movement={id:string;created_at:string;quantity_before:number;quantity_change:number;quantity_after:number;reason:string;notes:string|null;company_name:string|null;courier_name:string|null;product_name:string|null;total_count:number};
type FilterKey="company"|"courier"|"product"|"search"|"type"|"from"|"to";
const today=()=>new Date().toLocaleDateString("en-CA");
export default function InventoryMovementsPage(){
 const [data,setData]=useState<Movement[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[pagination,setPagination]=useState({pageIndex:0,pageSize:25}),[total,setTotal]=useState(0);
 const [company,setCompany]=useState(""),[courier,setCourier]=useState(""),[product,setProduct]=useState(""),[search,setSearch]=useState(""),[type,setType]=useState(""),[from,setFrom]=useState(today),[to,setTo]=useState(today);
 const [enabled,setEnabled]=useState<Record<FilterKey,boolean>>({company:false,courier:false,product:false,search:false,type:false,from:true,to:true});
 const filters=useMemo(()=>({p_company:enabled.company?company||null:null,p_courier:enabled.courier?courier||null:null,p_product:enabled.product?product||null:null,p_search:enabled.search?search||null:null,p_movement_type:enabled.type?type||null:null,p_from:enabled.from&&from?`${from}T00:00:00`:null,p_to:enabled.to&&to?`${to}T23:59:59.999`:null,p_limit:pagination.pageSize,p_offset:pagination.pageIndex*pagination.pageSize}),[company,courier,product,search,type,from,to,enabled,pagination]);
 useEffect(()=>{setLoading(true);Promise.resolve(createClient().rpc("get_inventory_movements_page",filters)).then(({data,error})=>{if(error){setError(error.message);setData([]);setTotal(0);return;}const rows=(data??[]) as Movement[];setData(rows);setTotal(Number(rows[0]?.total_count??0));setError("");}).finally(()=>setLoading(false));},[filters]);
 const columns=useMemo<MRT_ColumnDef<Movement>[]>(()=>[{accessorKey:"created_at",header:"Fecha",Cell:({cell})=>new Date(String(cell.getValue())).toLocaleString("es-CR")},{id:"type",header:"Tipo",Cell:({row})=><Chip size="small" color={row.original.quantity_change>0?"success":"error"} label={row.original.quantity_change>0?"Entrada":"Salida"}/>},{accessorKey:"company_name",header:"Empresa"},{accessorKey:"courier_name",header:"Mensajero"},{accessorKey:"product_name",header:"Producto"},{accessorKey:"quantity_before",header:"Inicial"},{accessorKey:"quantity_change",header:"Movimiento",Cell:({cell})=><span className={Number(cell.getValue())>0?"font-semibold text-green-600":"font-semibold text-red-600"}>{Number(cell.getValue())>0?"+":""}{String(cell.getValue())}</span>},{accessorKey:"quantity_after",header:"Final"},{accessorKey:"reason",header:"Motivo"},{accessorKey:"notes",header:"Notas"}],[]);
 const input="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-700 dark:bg-slate-950";
 const change=(key:FilterKey,setter:(v:string)=>void)=>(e:ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>{setter(e.target.value);setEnabled(x=>({...x,[key]:true}));setPagination(p=>({...p,pageIndex:0}));};
 const title=(key:FilterKey,label:string)=><span className="flex items-center gap-2"><input type="checkbox" checked={enabled[key]} onChange={e=>{setEnabled(x=>({...x,[key]:e.target.checked}));setPagination(p=>({...p,pageIndex:0}));}}/>{label}</span>;
 const reset=()=>{setCompany("");setCourier("");setProduct("");setSearch("");setType("");setFrom(today());setTo(today());setEnabled({company:false,courier:false,product:false,search:false,type:false,from:true,to:true});setPagination(p=>({...p,pageIndex:0}));};
 return <div className="space-y-4 p-2 sm:p-6"><section className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h2 className="font-semibold">Filtros de movimientos</h2><p className="mb-3 text-sm text-slate-600 dark:text-slate-400">Marca el checkbox para aplicar un filtro. Los valores se conservan aunque lo desactives. Por defecto se consulta hoy.</p><div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-medium">{title("company","Empresa")}<input className={input} value={company} onChange={change("company",setCompany)}/></label><label className="text-sm font-medium">{title("courier","Mensajero")}<input className={input} value={courier} onChange={change("courier",setCourier)}/></label><label className="text-sm font-medium">{title("product","Producto")}<input className={input} value={product} onChange={change("product",setProduct)}/></label><label className="text-sm font-medium">{title("search","Motivo u observación")}<input className={input} value={search} onChange={change("search",setSearch)}/></label><label className="text-sm font-medium">{title("type","Tipo")}<select className={input} value={type} onChange={change("type",setType)}><option value="">Entradas y salidas</option><option value="entry">Solo entradas</option><option value="exit">Solo salidas</option></select></label><label className="text-sm font-medium">{title("from","Fecha desde")}<input className={input} type="date" value={from} onChange={change("from",setFrom)}/></label><label className="text-sm font-medium">{title("to","Fecha hasta")}<input className={input} type="date" value={to} onChange={change("to",setTo)}/></label><button type="button" onClick={reset} className="flex items-center justify-center gap-2 self-end rounded-lg border border-amber-500 bg-amber-50 p-3 font-medium text-amber-800 hover:bg-amber-100 dark:bg-amber-950/30 dark:text-amber-200"><RotateCcw size={17}/> Limpiar filtros</button></div></section>{error?<div className="rounded-xl border border-red-400 p-4 text-red-600">{error}</div>:<><div className="rounded-xl border border-cyan-300 bg-cyan-50 px-4 py-3 text-sm dark:border-cyan-900 dark:bg-cyan-950/30">BD · <strong>{total}</strong> movimientos coincidentes</div><MaterialReactTable {...standardMrtFeatures} columns={columns} data={data} localization={MRT_Localization_ES} manualPagination rowCount={total} state={{isLoading:loading,pagination}} onPaginationChange={setPagination} initialState={{density:"compact"}}/></>}</div>;
}
